"""add resolution to custom_provider_model

Revision ID: a89021f43d52
Revises: d67efd76058f
Create Date: 2026-04-23 17:52:54.487317

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "a89021f43d52"
down_revision: str | Sequence[str] | None = "d67efd76058f"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("custom_provider_model", schema=None) as batch_op:
        batch_op.add_column(sa.Column("resolution", sa.String(length=64), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("custom_provider_model", schema=None) as batch_op:
        batch_op.drop_column("resolution")

    # ### end Alembic commands ###
