"""add supported_durations to custom_provider_model

Revision ID: c9b24204c0de
Revises: bda1ff338ff3
Create Date: 2026-04-06 15:10:09.936628

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "c9b24204c0de"
down_revision: str | Sequence[str] | None = "bda1ff338ff3"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("custom_provider_model", schema=None) as batch_op:
        batch_op.add_column(sa.Column("supported_durations", sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("custom_provider_model", schema=None) as batch_op:
        batch_op.drop_column("supported_durations")

    # ### end Alembic commands ###
